### ISSUE TITLE
Doesn't work under Raspbian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by bubba198** [myDevicesIoT/cayenne-plugin-sensehat#1]
The plug-in installs just fine, no errors, however none of the sensors show up. This is the latest buster image freshly copied onto a new SD card straight from Rpi site:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

Log file below, it seems to me that the plug-in can't communicate with the bare metal Hat, possibly due to the buster image? Otherwise the Hat is fully functional, I can read sensors from small py example code just fine.

```
2020-07-03 06:35:11 - myDevices - INFO - Sensors info: []
2020-07-03 06:35:11 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:11 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:11 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:11 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:11 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:11 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:11 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:11 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:11 - myDevices - INFO - Send changed data: [{'sys:cpu;load': 16.5}, {'sys:cpu;temp': 48.85}, {'sys:ram;usage': 302604288}, {'sys:storage:/;usage': 3119116288}, {'sys:net;ip': '192.168.166.94'}, {'dev:sensehat:4': 0}, {'dev:sensehat:5': 0.0}] + sys:gpio
2020-07-03 06:35:26 - myDevices - ERROR - Failed to get sensor data: Temperature GGMMo5GMCJpwLKG
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/myDevices-2.0.4-py3.7.egg/myDevices/sensors/sensors.py", line 322, in SensorsInfo
    value = self.CallDeviceFunction(func)
  File "/usr/local/lib/python3.7/dist-packages/myDevices-2.0.4-py3.7.egg/myDevices/sensors/sensors.py", line 264, in CallDeviceFunction
    result = func(*args)
  File "/usr/local/lib/python3.7/dist-packages/myDevices-2.0.4-py3.7.egg/myDevices/devices/sensor/__init__.py", line 116, in getCelsius
    return self.__getCelsius__()
  File "/usr/local/lib/python3.7/dist-packages/myDevices-2.0.4-py3.7.egg/myDevices/devices/sensor/tmpXXX.py", line 48, in __getCelsius__
    d = self.readBytes(2)
  File "/usr/local/lib/python3.7/dist-packages/myDevices-2.0.4-py3.7.egg/myDevices/devices/bus.py", line 157, in readBytes
    return bytearray(self.readDevice(size))
  File "/usr/local/lib/python3.7/dist-packages/myDevices-2.0.4-py3.7.egg/myDevices/devices/bus.py", line 153, in readDevice
    return os.read(self.fd, size)
OSError: [Errno 121] Remote I/O error
2020-07-03 06:35:26 - myDevices - INFO - Sensors info: []
2020-07-03 06:35:26 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:26 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:26 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:26 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:26 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:26 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:26 - myDevices - INFO - Sense HAT service connection refused
2020-07-03 06:35:26 - myDevices - ERROR - [Errno 111] Connection refused
2020-07-03 06:35:26 - myDevices - INFO - Send changed data: [{'sys:cpu;load': 0.0}, {'sys:cpu;temp': 45.084}, {'sys:ram;usage': 302784512}]

```

**Comment by d1g33k** [comment]
Facing quite the same issue on the 64-bit beta OS. Only the actuators are available on the dashboard and none of the sensors are being read by the plugin, though everything is dandy on the Sense Hat itself.

**Comment by bubba198** [comment]
@d1g33k I had a very long exchange with someone on their forums, at the end of the day the install instructions clearly diverge from reality, I was directed to edit a file, etc but at the end of the day -- it worked!

[https://community.mydevices.com/t/sense-hat-support-on-raspberry-pi/163/62](url)

The short and sweet version:
```

cd /etc/myDevices/plugins/cayenne-plugin-sensehat

sudo sed -i 's/True/False/' /etc/myDevices/plugins/cayenne-plugin-sensehat/sensehat/startservice.py

sudo python3 setup.py install

sudo service myDevices restart
```

**Comment by jburhenn** [comment]
@d1g33k If those commands work for you please let us know and we can include that edit in the code.

If it doesn't you might also try reinstalling the sense-hat package with `sudo apt-get install --reinstall sense-hat` and see if that helps.

**Comment by bubba198** [comment]
@d1g33k sorry for the delayed ping, yes that worked and solved the issue, thank you so much
